cnp_settings:
  training_iterations: 3540
  max_context_points: 10000
  max_target_points: 2000
  context_is_subset: True
  batch_size: 1
  config_wise: False
  version: v1.6
  use_data_augmentation: mixup #"smote" #False #"mixup"
  use_beta: [0.1,0.1] # uniform => None, beta => [a,b] U-shape [0.1,0.1] Uniform [1.,1.] falling [0.2,0.5] rising [0.2,0.5]
  signal_to_background_ratio: "" # "_1to4" # used for smote augmentation
  ratio_testing_vs_training: 1/40
  plot_after: 500

simulation_settings:
  # all available x config/ physics parameters are ["radius","thickness","npanels","theta","length","height","z_offset","volume","nC_Ge77","time_0[ms]","x_0[m]","y_0[m]","z_0[m]","px_0[m]","py_0[m]","pz_0[m]","ekin_0[eV]","edep_0[eV]","time_t[ms]","x_t[m]","y_t[m]","z_t[m]","px_t[m]","py_t[m]","pz_t[m]","ekin_t[eV]","edep_t[eV]","nsec"]
  # Comment: if using data version v1.1 for training, "radius","thickness","npanels","theta","length" is probably necessary 
  design_parameters: ["radius","thickness","npanels","theta","length"]
  event_specific_parameters: ["r_0[m]","z_0[m]","time_t[ms]","r_t[m]","z_t[m]","L_t[m]","ln(E0vsET)","edep_t[eV]","nsec"]
  y_raw_cnp: total_nC_Ge77[cts]
  y_raw_data_gen: nC_Ge77
  version_lf: v1.4
  version_hf: v1.1
  file_prefix: neutron
  nsamples_lf: 50000
  nsamples_hf: 10000000

